### ISSUE TITLE
Login: Can't login

### ISSUE THREAD

**Issue by deimantastumas** [MantasDemenius/BGT-backend#4]
## What happened
I've tried logging into my favourite website, sadly, unsuccessfully.

## Environment
- Google Chrome
- Credentials: admin admin
- TempleOS

## How to reproduce
- Go to your all time favourite BGT website
- Try logging in
- Fail

## What I expected
To login successfully

## Ideas
Maybe username is case sensitive :?

**Comment by deimantastumas** [comment]
Any updates? I really want to log in

**Comment by MantasDemenius** [comment]
New release will be tomorrow, try again then

**Comment by MantasDemenius** [comment]
Duplicate
